Repository majorbalintistvan/Proj1-deeprockgalactic-9C, pull requests merged in 2023-02, with the labels that each got.

#22 responsive szövegek
  Index.html
  stílus.css
Labels: formázás

#25 megcsináltam az oldal hátterét, a szöveggel még kell kezdeni valamit
  Index.html
  stílus.css
Labels: formázás

#26 elkezdtem, de még nem működik
  Források/kezdőknekkell
  Index.html
  kezdőknek.html
Labels: bogár :bug:, kérdés :question:, formázás

#27 Formáztam a főoldalon
  Index.html
  stílus.css
Labels: formázás

#32 28 források gyűjtése a fegyvertárhoz
  Források/Fegyvertár/felderítő/kisegítő eszközök/Csáklyavető.txt
  Források/Fegyvertár/felderítő/kisegítő eszközök/Flare_Gun_Animations.webm
  Források/Fegyvertár/felderítő/kisegítő eszközök/GearGraphic_GraplingHook.webp
  Források/Fegyvertár/felderítő/kisegítő eszközök/Jelzőpisztoly.txt
  Források/Fegyvertár/fúrós/elsődleges/CRSPR_Flamethrower_Animations.webm
  Források/Fegyvertár/fúrós/elsődleges/Cryo_Cannon_Animations.webm
  Források/Fegyvertár/fúrós/elsődleges/PRZSL lángszóró.txt
  Források/Fegyvertár/fúrós/elsődleges/cyro ágyú.txt
Labels: gyűjtés

#35 karakterinformációk kigyűjtve
  Források/karakterinfó/felderítő
  Források/karakterinfó/fúrós
  Források/karakterinfó/lövész
  Források/karakterinfó/mérnök
Labels: gyűjtés

#46 kis változtatás, óra végei állás
  kezdőknek.html
  küldetésháttér.jpg
  stílus.css
Labels: formázás

#48 Kész a kvíz oldal
  Index.html
  kezdőknek.html
  kvíz.html
  script.js
  stílus.css
Labels: sűrgős :exclamation:, kéne még valami, kérdés :question:

#51 küldetések kezdetleges
  kezdőknek.html
  stílus.css
Labels: formázás
