Repository majorbalintistvan/Proj1-deeprockgalactic-9C, pull requests merged in 2023-03, with the labels that each got.

#53 kész küldetések
  Források/képek/küldetésképek/tojásmassza.webp
  Források/küldetések.txt
  kezdőknek.html
  stílus.css
Labels: kő és szikla, kérdés :question:

#55 1 a 10-ből. A másikat csináltam, eddig jutottam
  Források/bolygórégiók.txt
Labels: gyűjtés

#57 most már 10 kérdés van
  kezdőknek.html
  script.js
Labels: formázás

#59 Megvan minden forrás és a sablon
  Források/bolygórégiók.txt
  Források/képek/bolygórégióképek/AzúrPagony.webp
  Források/képek/bolygórégióképek/BarlangiAngyal.webp
  Források/képek/bolygórégióképek/ásványok/Kroppa.webp
  Források/képek/bolygórégióképek/ásványok/Umanit.webp
  bolygórégiókháttér.jpg
  kezdőknek.html
  stílus.css
Labels: kő és szikla

#61 Jól halad a Bolygórégiók
  Források/bolygórégiók.txt
  Források/képek/bolygórégióképek/Gombamocsarak.webp
  Források/képek/bolygórégióképek/Hőzóna.webp
  Források/képek/bolygórégióképek/Jég.webp
  Források/képek/bolygórégióképek/Kristálybarlangok.webp
  Források/képek/bolygórégióképek/SűrűBiozóna.webp
  Források/képek/bolygórégióképek/növényvilág.webp
  Források/képek/bolygórégióképek/sokkkristály.webp
  Források/képek/bolygórégióképek/trutyi.webp
  Források/képek/bolygórégióképek/ásványok/Bizmor.webp
  Források/képek/bolygórégióképek/ásványok/Jádiz.webp
  Források/képek/bolygórégióképek/ásványok/Magnit.webp
  kezdőknek.html
  stílus.css
Labels: kő és szikla

#63 készen van a bolygórégiók oldalrész
  Források/képek/bolygórégióképek/LávaGejzír.webp
  Források/képek/bolygórégióképek/Magmamag.webp
  Források/képek/bolygórégióképek/OdvasBolygófa.webp
  Források/képek/bolygórégióképek/RadioaktívZóna.webp
  Források/képek/bolygórégióképek/Radioaktív_kristályok.webp
  Források/képek/bolygórégióképek/Sóbányák.webp
  Források/képek/bolygórégióképek/homokbánya.webp
  Források/képek/bolygórégióképek/homokvihar.webp
  Források/képek/bolygórégióképek/tüskék.webp
  Források/képek/bolygórégióképek/veszélyeskristály.webp
  Források/képek/bolygórégióképek/ásványok/Enorgyöngy.webp
  kezdőknek.html
Labels: sűrgős :exclamation:, kő és szikla

#65 magyarosítottam a főoldal szövegét
  Index.html
Labels: formázás

#67 kész a tartalomjegyzék
  kezdőknek.html
Labels: sűrgős :exclamation:

#70 átdolgoztam a karakterek oldalrészt
  kezdőknek.html
  stílus.css
Labels: sűrgős :exclamation:

#72 kitöröltem a tartótxt-t
  kezdőknek.html
  tartó.txt
  tartó2.txt
Labels: sűrgős :exclamation:

#77 73 tényleg utolsó simitások
  Források/képek/1286244.jpg
  Források/képek/Magma.jpg
  Források/képek/deeprockgalactic_3629293.jpg
  Index.html
  Képkollázs.html
  fegyvertár-elosztó.html
  fegyvertár-felderítő.html
  fegyvertár-fúrós.html
  fegyvertár-lövész.html
  fegyvertár-mérnök.html
  kezdőknek.html
  kvíz.html
  script.js
  stílus.css
Labels: formázás

#75 valószínüleg már végleges a kezdőknek lap formázása
  kezdőknek.html
  stílus.css
Labels: formázás

#79 Átírtam a főbb címeket
  Index.html
  fegyvertár-fúrós.html
  fegyvertár-lövész.html
  fegyvertár-mérnök.html
Labels: formázás

#82 Kijavítottam a hibát
  Index.html
Labels: bogár :bug:

#83 Még egy kis hiba javítás
  Index.html
  stílus.css
Labels: bogár :bug:, formázás

#85 Bence észrevételei szerint módosítottunk
  Index.html
  kvíz.html
  stílus.css
Labels: formázás
